<?php

include_once('scholar_ediario.features.inc');

/**
 * Implementation of hook_block
 */
function scholar_ediario_block($op = 'list', $delta = false, $edit = array()){
  if ($op == 'list') {
    $blocks['rss']['info'] = t('RSS Feed - Link to subscribe to your newest ediario entries');
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 'rss':
        return _scholar_ediario_rss_wgt();
    }
  }
}

/**
 * Implementation of hook_context_links_alter().
 */
function scholar_ediario_context_links_alter(&$links) {
  if (!empty($links['ediario'])) {
    $links['ediario']['query'] = drupal_get_destination();
  }
}

/**
 * hook link_alter (admin at the end of links)
 */
function scholar_ediario_link_alter(&$links, $node){
  
  if (isset($links['ediario_usernames_ediario'])) {
    unset($links['ediario_usernames_ediario']);
  }
}


/**
 * Link to subscribe to the rss feed
 */
function _scholar_ediario_rss_wgt(){
  
  if ($image = theme('image', 'misc/feed.png', t('Syndicate content'), 'RSS')) {
    $block['content'] = l($image . " Subscribe", 'ediario/feed', array('html' => TRUE, 'attributes' => array('class' => 'feed-icon')));
  }
  return $block;
}
